name: release

on: workflow_dispatch

jobs:
  release:
    if: github.ref_type == 'branch' && (github.ref_name == 'main' || startsWith(github.ref_name, 'snapshot-'))
    runs-on: ubuntu-latest
    steps:
      - uses: dbstar-org/setup-maven@main
        with:
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
      - run: cat ~/.m2/settings.xml
      - name: Verify with Maven
        run: mvn -B -U clean verify
      - uses: dbstar-org/maven-settings-appender@main
        with:
          repositories: |-
            <repository>
              <id>github</id>
              <url>https://maven.pkg.github.com/${env.GITHUB_REPOSITORY_OWNER}/*</url>
            </repository>
            <repository>
              <id>github-actor</id>
              <url>https://maven.pkg.github.com/${env.GITHUB_ACTOR}/*</url>
            </repository>
          servers: |-
            <server>
              <id>github-actor</id>
              <username>${env.GITHUB_ACTOR}</username>
              <password>${env.GITHUB_TOKEN}</password>
            </server>
      - run: cat ~/.m2/settings.xml
