name: release

on: workflow_dispatch

jobs:
  release:
    if: github.ref_type == 'branch' && (github.ref_name == 'main' || startsWith(github.ref_name, 'snapshot-'))
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - id: setup-java
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'adopt'
      - run: cat ~/.m2/settings.xml
      - run: gpg -k
      - run: echo '${{ toJSON(github) }}'
      - run: echo '${{ toJSON(runner) }}'
