name: release

on: workflow_dispatch

jobs:
  release:
    if: github.ref_type == 'branch' && (github.ref_name == 'main' || startsWith(github.ref_name, 'snapshot-'))
    runs-on: ubuntu-latest
    steps:
      - uses: dbstar-org/setup-maven@v1
        with:
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}

      - name: Prepare Release
        env:
          GITHUB_TOKEN: ${{ github.token }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
        run: mvn -B -U release:prepare -P release,distribution-github

      - run: cp ${{ github.workspace }}/release.properties ${{ github.workspace }}/release.properties.bak

      - name: Perform Release to Github
        env:
          GITHUB_TOKEN: ${{ github.token }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
        run: mvn -B -U release:perform -P release,distribution-github

      - run: mv ${{ github.workspace }}/release.properties.bak ${{ github.workspace }}/release.properties

      - name: Perform Release to Ossrh
        env:
          GITHUB_TOKEN: ${{ github.token }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
          OSS_USERNAME: ${{ secrets.OSS_USERNAME }}
          OSS_PASSWORD: ${{ secrets.OSS_PASSWORD }}
        run: mvn -B -U release:perform -P release,distribution-ossrh